config/routes.rb
Rails.application.routes.draw do
  resources :categories,:soups

  root to:"categories#index"
  get '/allcategories',to:redirect("/")

  get "/soups/:id/toggle_featured",to:"soups#toggle_featured",as: :toggle_featured
  get "/secret_soups",to:"soups#secret_soups"
  get "/secret_soups_no",to:"soups#secret_soups_no",as: :secret_soups_no
  get "/admin",to:"soups#admin"
  get "/logout",to:"soups#logout",as: :logout

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :soups
  validates :name,presence:true,uniqueness:true
end

app/models/soup.rb
class Soup < ActiveRecord::Base
  belongs_to :category
  validates :name,presence:true,uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
      @categories = Category.all
    end
    def show
      @category = Category.find(params[:id])
    end
    def new

    end
    def edit

    end
    def update

    end
    def destroy

    end
end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
  before_action :fetch_soup,only:[:show,:edit,:update,:destroy,:toggle_featured]
    def show
      respond_to do |format|
        format.html
        format.json {render json:@soup}
      end
    end
    def index
      @soups = Soup.all

      respond_to do |format|
        format.json {render json:@soups}
      end
    end
    def new

    end
    def edit

    end
    def update

    end
    def destroy

    end
    def toggle_featured
      @soup.toggle!(:featured)
      flash[:notice]="Sucessfully changed the featured flag"
      redirect_to @soup

    end
    def secret_soups
      session[:vip]=true
      redirect_to root_path
    end
    def secret_soups_no
      session[:vip]=false
      redirect_to root_path
    end
    def admin
      session[:admin]=true
      redirect_to root_path
    end
    def logout
      session[:admin]=false
      redirect_to root_path
    end
    private
    def fetch_soup
      @soup = Soup.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/views/categories/index.html.erb
<h1>Soup Categories</h1>
<ul>
  <% @categories.each do |category| %>
  <li><%=link_to category.name,category%>(<%=category.soups.count%>) </li>
  <% end %>
  <%if session[:vip] %>
  <li>Super Secret Bouilon</li>
  <%end %>
</ul>
<%if session[:admin]%>
<%=link_to "Log out from admin",logout_path%>
<%end%>
<%if session[:vip] %>
<p><%=link_to "Hide secret",secret_soups_no_path %></p>
<%end %>

app/views/categories/show.html.erb
<h2><%=@category.name %></h2>

<ul>
  <% @category.soups.each do |soup| %>
    <li><%=link_to soup.name,soup %></li>
  <% end %>
</ul>


<p><%= link_to "Back to Soup Categories",categories_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Available Soups</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
  <p><%=flash[:notice]%></p>
<%end%>
<%= yield %>

</body>

</html>

app/views/soups/show.html.erb
<h1><%=@soup.name %></h1>
<%if @soup.featured? %>
  <p>This delicious soup is featured this month.</p>
<%else %>
  <p>This soup is not in season,so it kinda sucks right now.</p>
<%end %>
<%if session[:admin]==true %>
  <p><%= link_to "Toggle Featured",toggle_featured_path(@soup)%></p>
<% end %>
<p><%= link_to "Back to Soup Category",@soup.category%></p>